name: Build and Deploy Mods
on:
  schedule:
    - cron: '0 */1 * * *' # Every hour
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
jobs:
  build:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
      - name: Create/Restore PowerShell Module Cache
        uses: actions/cache@v3
        with:
          path: ~/Documents/PowerShell
          key: ${{ runner.os }}-powershell-${{ hashFiles('./*.ps1') }}${{ hashFiles('./*.psm1') }}${{ hashFiles('./*.psd1') }}
          restore-keys: |
            ${{ runner.os }}-powershell-
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Clone Mod Git Repositories
        uses: Amadevus/pwsh-script@v2
        with:
          script: ./clone.ps1;
      - name: Create/Restore NuGet Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Update Mods NuGet Dependencies
        uses: Amadevus/pwsh-script@v2
        with:
          script: ./update.ps1;
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build Mods
        uses: Amadevus/pwsh-script@v2
        with:
          script: ./build.ps1;
      - name: Combine Mods
        uses: Amadevus/pwsh-script@v2
        with:
          script: ./merge.ps1;
      - name: Generate Release Date Info
        uses: Amadevus/pwsh-script@v2
        id: date
        with:
          script: |
            Write-Host("::set-output name=result::$(Get-Date -Format 'dd/mm/yyyy HH:mm K')");
      - name: Release Assets
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Release - ${{ steps.date.outputs.result }}"
          files: |
            build/*.zip